version: "3.3"

services:
  srp-static:
    restart: always
    container_name: srp-static
    build:
      context: .
      args:
        - SRP_BUILDARG_CERT_FILE=./.static/cert.pem
        - SRP_BUILDARG_KEY_FILE=./.static/key.pem
        - SRP_BUILDARG_CONFIG_FILE=./.static/srp.yml
    ports:
      - "443:443"
    environment:
      - SRP_PORT=443
      - SRP_SSL_MODE=static
      - SRP_CERT_FILE=/app/cert.pem
      - SRP_KEY_FILE=/app/key.pem
      - SRP_CONF=/app/srp.yml
      - SRP_DEBUG=false
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

