
on: push
name: Go build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: run
        uses: cedrickring/golang-action@1.3.0
        env:
          PROJECT_PATH: "./app"
